elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  image: logstash:1.4.2
  command: logstash --pluginpath /home/logstash/lib/ -f /etc/logstash/conf.d/
  #command: logstash -f /etc/logstash/conf.d/
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/plugin/logstash-input-log4j2-5.1:/home/logstash
  ports:
    - "5000:5000"
    - "4560:4560"
    - "4561:4561"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
